twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        cat_pictures_path: '/uploads/catPictures'

when@test:
    twig:
        strict_variables: true
